### ISSUE TITLE
Issue with appimage on flatpak steam

### ISSUE THREAD

**Issue by successfully-failed** [TeamHypersomnia/Hypersomnia#289]
Hi, I've got problems with running the game from steam flatpak. After running everything from terminal, issue seems to be lack of FUSE library in steam runtime, which results in inability to run appimage. The solution would be to just include the binary. 

Here is a screenshot from the terminal:
![Zrzut ekranu_20240809_231156](https://github.com/user-attachments/assets/4d0fd07e-cf73-4ab1-94d1-f4b1f4a672e7)

**Comment by geneotech** [comment]
Hello, ``fuse`` must actually be installed manually so that any AppImage can be mounted in the first place - an AppImage cannot simply include ``fuse``. If you don't want to install it, you could always add ``--appimage-extract-and-run`` to the command line arguments in Steam options for Hypersomnia.
